version: '3.8'
services:
  app:
    image: openjdk:11
    container_name: "app"
    ports:
      - 8081:8081
    volumes:
      - ./target/bikes-0.0.1-SNAPSHOT.jar:/tmp/app.jar
    entrypoint:
      ["java","-jar","/tmp/app.jar"]
    depends_on:
      - db
      - keycloak
  db:
    container_name: "mongo"
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  keycloak:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    command:
      - "start-dev"
      - "-Dkeycloak.profile.feature.docker=enabled"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/tmp/realm-export.json"

volumes:
  mongo_data: